# coding: utf-8

# flake8: noqa

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "HealthApi",
    "LoadApi",
    "StoreApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AvgPrice",
    "BaseResponseSchema",
    "EventStoreStatsRequestSchema",
    "EventStoreType",
    "HTTPValidationError",
    "InputEventStatsSchema",
    "InputEventStatsSchemaSectionPricesValueInner",
    "InputPlaceSectionStats",
    "InputPriceChangeStats",
    "LocationInner",
    "MaxPrice",
    "MedianPrice",
    "MinPrice",
    "NewPrice",
    "OldPrice",
    "OverallMetrics",
    "OverallSingleMetrics",
    "PriceChangeSchema",
    "SeatInfo",
    "SectionStats",
    "SectionVolatilityMetrics",
    "SingleEventTime",
    "SingleVolatilityMetrics",
    "SortStatsBy",
    "StatsResponseSchema",
    "StatsSchema",
    "StatsTimeResponseSchema",
    "StatsTimeWindow",
    "StatsTrendingLastChangeResponseSchema",
    "StatsTrendingResponseSchema",
    "SummarySchema",
    "TrendingEvent",
    "TrendingEventPriceSchema",
    "TrendingEventTurnoverSchema",
    "ValidationError",
    "VolatilityMetrics",
]

# import apis into sdk package
from event_stats_client.api.health_api import HealthApi as HealthApi
from event_stats_client.api.load_api import LoadApi as LoadApi
from event_stats_client.api.store_api import StoreApi as StoreApi

# import ApiClient
from event_stats_client.api_response import ApiResponse as ApiResponse
from event_stats_client.api_client import ApiClient as ApiClient
from event_stats_client.configuration import Configuration as Configuration
from event_stats_client.exceptions import OpenApiException as OpenApiException
from event_stats_client.exceptions import ApiTypeError as ApiTypeError
from event_stats_client.exceptions import ApiValueError as ApiValueError
from event_stats_client.exceptions import ApiKeyError as ApiKeyError
from event_stats_client.exceptions import ApiAttributeError as ApiAttributeError
from event_stats_client.exceptions import ApiException as ApiException

# import models into sdk package
from event_stats_client.models.avg_price import AvgPrice as AvgPrice
from event_stats_client.models.base_response_schema import BaseResponseSchema as BaseResponseSchema
from event_stats_client.models.event_store_stats_request_schema import EventStoreStatsRequestSchema as EventStoreStatsRequestSchema
from event_stats_client.models.event_store_type import EventStoreType as EventStoreType
from event_stats_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from event_stats_client.models.input_event_stats_schema import InputEventStatsSchema as InputEventStatsSchema
from event_stats_client.models.input_event_stats_schema_section_prices_value_inner import InputEventStatsSchemaSectionPricesValueInner as InputEventStatsSchemaSectionPricesValueInner
from event_stats_client.models.input_place_section_stats import InputPlaceSectionStats as InputPlaceSectionStats
from event_stats_client.models.input_price_change_stats import InputPriceChangeStats as InputPriceChangeStats
from event_stats_client.models.location_inner import LocationInner as LocationInner
from event_stats_client.models.max_price import MaxPrice as MaxPrice
from event_stats_client.models.median_price import MedianPrice as MedianPrice
from event_stats_client.models.min_price import MinPrice as MinPrice
from event_stats_client.models.new_price import NewPrice as NewPrice
from event_stats_client.models.old_price import OldPrice as OldPrice
from event_stats_client.models.overall_metrics import OverallMetrics as OverallMetrics
from event_stats_client.models.overall_single_metrics import OverallSingleMetrics as OverallSingleMetrics
from event_stats_client.models.price_change_schema import PriceChangeSchema as PriceChangeSchema
from event_stats_client.models.seat_info import SeatInfo as SeatInfo
from event_stats_client.models.section_stats import SectionStats as SectionStats
from event_stats_client.models.section_volatility_metrics import SectionVolatilityMetrics as SectionVolatilityMetrics
from event_stats_client.models.single_event_time import SingleEventTime as SingleEventTime
from event_stats_client.models.single_volatility_metrics import SingleVolatilityMetrics as SingleVolatilityMetrics
from event_stats_client.models.sort_stats_by import SortStatsBy as SortStatsBy
from event_stats_client.models.stats_response_schema import StatsResponseSchema as StatsResponseSchema
from event_stats_client.models.stats_schema import StatsSchema as StatsSchema
from event_stats_client.models.stats_time_response_schema import StatsTimeResponseSchema as StatsTimeResponseSchema
from event_stats_client.models.stats_time_window import StatsTimeWindow as StatsTimeWindow
from event_stats_client.models.stats_trending_last_change_response_schema import StatsTrendingLastChangeResponseSchema as StatsTrendingLastChangeResponseSchema
from event_stats_client.models.stats_trending_response_schema import StatsTrendingResponseSchema as StatsTrendingResponseSchema
from event_stats_client.models.summary_schema import SummarySchema as SummarySchema
from event_stats_client.models.trending_event import TrendingEvent as TrendingEvent
from event_stats_client.models.trending_event_price_schema import TrendingEventPriceSchema as TrendingEventPriceSchema
from event_stats_client.models.trending_event_turnover_schema import TrendingEventTurnoverSchema as TrendingEventTurnoverSchema
from event_stats_client.models.validation_error import ValidationError as ValidationError
from event_stats_client.models.volatility_metrics import VolatilityMetrics as VolatilityMetrics

