# coding: utf-8

# flake8: noqa
"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from event_stats_client.models.avg_price import AvgPrice
from event_stats_client.models.base_response_schema import BaseResponseSchema
from event_stats_client.models.event_store_stats_request_schema import EventStoreStatsRequestSchema
from event_stats_client.models.event_store_type import EventStoreType
from event_stats_client.models.http_validation_error import HTTPValidationError
from event_stats_client.models.input_event_stats_schema import InputEventStatsSchema
from event_stats_client.models.input_event_stats_schema_section_prices_value_inner import InputEventStatsSchemaSectionPricesValueInner
from event_stats_client.models.input_place_section_stats import InputPlaceSectionStats
from event_stats_client.models.input_price_change_stats import InputPriceChangeStats
from event_stats_client.models.location_inner import LocationInner
from event_stats_client.models.max_price import MaxPrice
from event_stats_client.models.median_price import MedianPrice
from event_stats_client.models.min_price import MinPrice
from event_stats_client.models.new_price import NewPrice
from event_stats_client.models.old_price import OldPrice
from event_stats_client.models.overall_metrics import OverallMetrics
from event_stats_client.models.overall_single_metrics import OverallSingleMetrics
from event_stats_client.models.price_change_schema import PriceChangeSchema
from event_stats_client.models.seat_info import SeatInfo
from event_stats_client.models.section_stats import SectionStats
from event_stats_client.models.section_volatility_metrics import SectionVolatilityMetrics
from event_stats_client.models.single_event_time import SingleEventTime
from event_stats_client.models.single_volatility_metrics import SingleVolatilityMetrics
from event_stats_client.models.sort_stats_by import SortStatsBy
from event_stats_client.models.stats_response_schema import StatsResponseSchema
from event_stats_client.models.stats_schema import StatsSchema
from event_stats_client.models.stats_time_response_schema import StatsTimeResponseSchema
from event_stats_client.models.stats_time_window import StatsTimeWindow
from event_stats_client.models.stats_trending_last_change_response_schema import StatsTrendingLastChangeResponseSchema
from event_stats_client.models.stats_trending_response_schema import StatsTrendingResponseSchema
from event_stats_client.models.summary_schema import SummarySchema
from event_stats_client.models.trending_event import TrendingEvent
from event_stats_client.models.trending_event_price_schema import TrendingEventPriceSchema
from event_stats_client.models.trending_event_turnover_schema import TrendingEventTurnoverSchema
from event_stats_client.models.validation_error import ValidationError
from event_stats_client.models.volatility_metrics import VolatilityMetrics

