# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class SingleEventTime(BaseModel):
    """
    SingleEventTime
    """ # noqa: E501
    total_added: StrictInt
    total_removed: Annotated[int, Field(strict=True, ge=0)]
    total_updated: Annotated[int, Field(strict=True, ge=0)]
    liquidity: Union[StrictFloat, StrictInt]
    availability_ratio: Union[StrictFloat, StrictInt]
    marked_change_ratio: Union[StrictFloat, StrictInt]
    event_id: StrictStr
    last_updated: datetime
    __properties: ClassVar[List[str]] = ["total_added", "total_removed", "total_updated", "liquidity", "availability_ratio", "marked_change_ratio", "event_id", "last_updated"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SingleEventTime from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SingleEventTime from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "total_added": obj.get("total_added"),
            "total_removed": obj.get("total_removed"),
            "total_updated": obj.get("total_updated"),
            "liquidity": obj.get("liquidity"),
            "availability_ratio": obj.get("availability_ratio"),
            "marked_change_ratio": obj.get("marked_change_ratio"),
            "event_id": obj.get("event_id"),
            "last_updated": obj.get("last_updated")
        })
        return _obj


