# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SortStatsBy(str, Enum):
    """
    SortStatsBy
    """

    """
    allowed enum values
    """
    TOTAL_ADDED = 'total_added'
    TOTAL_REMOVED = 'total_removed'
    TOTAL_UPDATED = 'total_updated'
    LIQUIDITY = 'liquidity'
    AVAILABILITY_RATIO = 'availability_ratio'
    MARKED_CHANGE_RATIO = 'marked_change_ratio'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SortStatsBy from a JSON string"""
        return cls(json.loads(json_str))


