# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from event_stats_client.models.trending_event_price_schema import TrendingEventPriceSchema
from event_stats_client.models.trending_event_turnover_schema import TrendingEventTurnoverSchema
from typing import Optional, Set
from typing_extensions import Self

class StatsTrendingLastChangeResponseSchema(BaseModel):
    """
    StatsTrendingLastChangeResponseSchema
    """ # noqa: E501
    turnover_events: List[TrendingEventTurnoverSchema]
    price_events: List[TrendingEventPriceSchema]
    __properties: ClassVar[List[str]] = ["turnover_events", "price_events"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StatsTrendingLastChangeResponseSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in turnover_events (list)
        _items = []
        if self.turnover_events:
            for _item_turnover_events in self.turnover_events:
                if _item_turnover_events:
                    _items.append(_item_turnover_events.to_dict())
            _dict['turnover_events'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in price_events (list)
        _items = []
        if self.price_events:
            for _item_price_events in self.price_events:
                if _item_price_events:
                    _items.append(_item_price_events.to_dict())
            _dict['price_events'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StatsTrendingLastChangeResponseSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "turnover_events": [TrendingEventTurnoverSchema.from_dict(_item) for _item in obj["turnover_events"]] if obj.get("turnover_events") is not None else None,
            "price_events": [TrendingEventPriceSchema.from_dict(_item) for _item in obj["price_events"]] if obj.get("price_events") is not None else None
        })
        return _obj


