# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from event_stats_client.models.overall_metrics import OverallMetrics
from event_stats_client.models.section_volatility_metrics import SectionVolatilityMetrics
from typing import Optional, Set
from typing_extensions import Self

class VolatilityMetrics(BaseModel):
    """
    VolatilityMetrics
    """ # noqa: E501
    section: Dict[str, SectionVolatilityMetrics]
    overall: OverallMetrics
    __properties: ClassVar[List[str]] = ["section", "overall"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VolatilityMetrics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in section (dict)
        _field_dict = {}
        if self.section:
            for _key_section in self.section:
                if self.section[_key_section]:
                    _field_dict[_key_section] = self.section[_key_section].to_dict()
            _dict['section'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of overall
        if self.overall:
            _dict['overall'] = self.overall.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VolatilityMetrics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "section": dict(
                (_k, SectionVolatilityMetrics.from_dict(_v))
                for _k, _v in obj["section"].items()
            )
            if obj.get("section") is not None
            else None,
            "overall": OverallMetrics.from_dict(obj["overall"]) if obj.get("overall") is not None else None
        })
        return _obj


